<map version="0.9.0">
<!-- Mind Map generated by the mindmap ruby gem -->
 <node CREATED="1320021898358" ID="scenario_Base_node_goes_here1554" MODIFIED="132002189833" TEXT="Base node goes here">
  <node CREATED="1320021898581" ID="scenario_one1599" MODIFIED="1320021898538" TEXT="one" FOLDED="true">
    <node CREATED="1320021898682" ID="scenario_one_one686" MODIFIED="1320021898258" TEXT="one.one" FOLDED="true">
      <node CREATED="1320021898685" ID="scenario_one_one_one2601" MODIFIED="1320021898218" TEXT="one.one.one"/>
    </node>
    <node CREATED="1320021898376" ID="scenario_one_two456" MODIFIED="1320021898973" TEXT="one.two" FOLDED="true">
      <node CREATED="1320021898404" ID="scenario_one_two_one2916" MODIFIED="1320021898820" TEXT="one.two.one"/>
    </node>
  </node>
  <node CREATED="1320021898377" ID="scenario_two857" MODIFIED="1320021898737" TEXT="two" FOLDED="true">
    <node CREATED="1320021898403" ID="scenario_two_one2933" MODIFIED="1320021898806" TEXT="two.one"/>
    <node CREATED="1320021898228" ID="scenario_two_one1357" MODIFIED="1320021898873" TEXT="two.one"/>
    <node CREATED="1320021898571" ID="scenario_two_one1275" MODIFIED="1320021898565" TEXT="two.one"/>
  </node>
  <node CREATED="1320021898222" ID="scenario_three1639" MODIFIED="1320021898156" TEXT="three" FOLDED="true">
    <node CREATED="1320021898681" ID="scenario_three1966" MODIFIED="1320021898650" TEXT="three"/>
  </node>
 </node>
</map>
