<map version="0.9.0">
<!-- Mind Map generated by the mindmap ruby gem -->
 <node CREATED="1319872837486" ID="scenario_Base_node_goes_here2652" MODIFIED="1319872837477" TEXT="Base node goes here">
  <node CREATED="1319872837808" ID="scenario_one1401" MODIFIED="1319872837666" TEXT="one" FOLDED="true">
    <node CREATED="1319872837889" ID="scenario_one_one2378" MODIFIED="1319872837405" TEXT="one.one" FOLDED="true">
      <node CREATED="1319872837355" ID="scenario_one_one_one2412" MODIFIED="131987283717" TEXT="one.one.one"/>
    </node>
    <node CREATED="1319872837819" ID="scenario_one_two181" MODIFIED="1319872837577" TEXT="one.two" FOLDED="true">
      <node CREATED="1319872837468" ID="scenario_one_two_one2876" MODIFIED="1319872837222" TEXT="one.two.one"/>
    </node>
  </node>
  <node CREATED="1319872837824" ID="scenario_two1456" MODIFIED="1319872837428" TEXT="two" FOLDED="true">
    <node CREATED="1319872837280" ID="scenario_two_one2050" MODIFIED="1319872837163" TEXT="two.one"/>
    <node CREATED="1319872837471" ID="scenario_two_one79" MODIFIED="1319872837347" TEXT="two.one"/>
    <node CREATED="1319872837359" ID="scenario_two_one945" MODIFIED="1319872837534" TEXT="two.one"/>
  </node>
  <node CREATED="1319872837301" ID="scenario_three1135" MODIFIED="1319872837774" TEXT="three" FOLDED="true">
    <node CREATED="1319872837295" ID="scenario_three312" MODIFIED="1319872837726" TEXT="three"/>
  </node>
 </node>
</map>
